### ISSUE TITLE
Linear Regression + MNIST Code 업로드

### ISSUE THREAD

**Issue by ghost** [Jamjomjara/snu-artoon#1]
- [Linear Regression](https://www.tensorflow.org/get_started/get_started)
- [MNIST For ML Beginners](https://www.tensorflow.org/get_started/mnist/beginners)

페이지에 소개되어 있는 예제 코드와 간단한 설명(?)을 업로드했습니다.

일단은 `study/tensorflow` 브랜치에 업로드했으나, 추후 브랜치나 이슈 라벨 등을 수정할 필요가 있을 것 같습니다.

**Comment by Jamjomjara** [comment]
@barlias 오오 척척 잘해가고 있군요!

**Comment by ghost** [comment]
@Jamjomjara 우와 감사합니다 ㅎㅎ
