### ISSUE TITLE
3/17 회의록

### ISSUE THREAD

**Issue by Jamjomjara** [Jamjomjara/snu-artoon#2]
- 개인별 담당영역을 정해서 학습하고 멤버와 함께 공유한다.
  - 사물인식 : 강민지
  - AR 앱개발 : 원종훈, 핌언
- 3/31 스펙 발표
  - 컨텐츠 선정 -> 기존 AR툰 사용
- 정기 미팅 -> 간단한건은 가급적 온라인을 통해 진행한다.
- 진행 내용은 Github에 올려 공유한다.

**Comment by pptnz** [comment]
학교에 제출하기 위해 한글 파일로 만들었습니다.
