### ISSUE TITLE
스펙 발표(3/31)를 위한 웹툰 원고 요청드립니다.

### ISSUE THREAD

**Issue by pptnz** [Jamjomjara/snu-artoon#5]
3월 31일에 있는 스펙 발표 시 웹툰 원고를 함께 제시하여 프로젝트를 더욱 명확하게 전달하고 싶습니다.
따라서 어떤 웹툰 원고를 사용할지 선정해야 합니다.
선정해주시거나 보내주시면 좋겠습니다.
감사합니다.

**Comment by Jamjomjara** [comment]
@pptnz 답변이 늦어서 죄송합니다. 일단 작품은 "폰령 - 1화 여관201호'로 진행 하려고 합니다. (AR툰은 앱으로만 확인이 가능합니다.) 네이버원고 이미지는 따로 전달 드리겠습니다~

**Comment by Jamjomjara** [comment]
@pptnz 일단 진행 플로우는 세로 스크롤 형태로 원고를 보다가 마지막 컷을 보고 AR모드로 구동되는 형태면 될것 같습니다.

**Comment by pptnz** [comment]
@Jamjomjara 네, 알겠습니다. 감사합니다!
