### ISSUE TITLE
스펙 발표를 위한 여러 가지 사항에 대해 문의드립니다.

### ISSUE THREAD

**Issue by pptnz** [Jamjomjara/snu-artoon#6]
3월 31일에 있을 스펙발표를 위해 몇 가지 문의 드릴 것이 있습니다.
- 발표 중간에 스펙에 관한 내용이 있어, **회사 평가서**를 주실 수 있는지 여쭤보고 싶습니다.
- **사물 인식에 사용할 사물**은 어떤 것이 될까요? 정확하게 설정하지 않으셨다면 단순한 예시라도 좋을 것 같습니다. 프로젝트의 목표를 구체적으로 전하기 위해 필요합니다.
- 머신 러닝은 **어떤 방향으로** 공부하면 좋을까요? 프로젝트에 대한 Approach(예, 기본적으로 사용되는 알고리즘 등)에 대해 발표해야 합니다.

목요일 자정까지 학교로 발표 자료를 제출해야 합니다. 이에 오늘은 각자 분업한 내용, 현재의 상황 등 가능한 내용에 대한 발표 자료를 만들고 있습니다. 오늘 작업한 내용은 오늘 자정에 올리겠습니다. 다소 빠듯한 일정이지만 혹시 시간이 되신다면 검토해주세요. 이렇게 갑작스럽게 부탁드리게 되어 죄송합니다.

감사합니다.

**Comment by Jamjomjara** [comment]
@pptnz 답변드립니다~
- 평가서는 원고와 함께 오늘 메일로 드리겠습니다.
- 원고 내용을 보면 알겠지만 내용상 귀신이 인물의 옆에 나타납니다. 그래서 인식대상을 인물(사람)로 정했으면 합니다.
- 사물에 대한 인식을 위해서는 딥러닝에서 컴퓨터비전 분야에 많이 활용되는 CNN으로 구성을 해야합니다.(Convolutional Neural Network) 지난번 MNIST 과제를 다중계층신경망으로 풀어보면 도움이 될것 같습니다.

**Comment by ghost** [comment]
@Jamjomjara 빠른 답변 정말 감사합니다! 열심히 발표 자료 준비하도록 하겠습니다 :)

**Comment by ghost** [comment]
@Jamjomjara 이미지셋과 평가표는 잘 받았습니다! 감사합니다.
현재 발표 자료 작업이 지연되어 업로드 시간이 내일로 미뤄질 것 같습니다. 죄송합니다. 열심히 작업하도록 하겠습니다.
